---
fabric_name: SITE1_FABRIC

# Set Design Type to L2ls
design:
  type: l2ls

# Repeat MLAG addressing between pairs
fabric_ip_addressing:
  mlag:
    algorithm: same_subnet

##################################################################
# Underlay Routing Protocol - ran on Spines
##################################################################

underlay_routing_protocol: OSPF
